# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e495e3154fe4ddd3929fcb88d8a3f06f9d5e880392b18b6d26c76099dba9f417b0cec94241b6219cce70ccbece8f51639ff22726774d4519a07bb2a58d1815b7

test:
  secret_key_base: 77da47c4edbb15f78c17f70881771e69db0b65544b488bcdfbb6eccf207a96f28805da749cf5d9b18101dc68ab1e6adfc42b458d28118105291af91d08ef8d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
